---
X_No_Archive: Yes
abstract: 'Build and install SDL3'
author:
  - 'Sanko Robinson <sanko@cpan.org>'
build_requires:
  Test2::V0: '0'
configure_requires:
  Alien::Build: '0'
  Alien::Build::MM: '0'
  Alien::cmake3: '0'
  Archive::Extract: '0.88'
  Archive::Tar: '3.02'
  Archive::Zip: '0'
  CPAN::Meta: '0'
  CPAN::Requirements::Dynamic: '0'
  Capture::Tiny: '0'
  Compress::Zlib: '2.204'
  Config: '0'
  Devel::CheckBin: '0'
  ExtUtils::Helpers: '0.028'
  ExtUtils::Install: '0'
  ExtUtils::InstallPaths: '0.002'
  File::Basename: '0'
  File::Path: '0'
  File::Spec::Functions: '0'
  Getopt::Long: '2.36'
  HTTP::Tiny: '0'
  IO::Socket::SSL: '1.42'
  IO::Zlib: '1.14'
  JSON::PP: '2'
  Net::SSLeay: '1.49'
  Path::Tiny: '0'
  PkgConfig: '0'
dynamic_config: 0
generated_by: 'App::mii v1.0.0, CPAN::Meta::Converter version 2.150012'
keywords: []
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-SDL3
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Alien::SDL3:
    file: lib/Alien/SDL3.pm
    version: v3.4.2
requires:
  Carp: '0'
  Config: '0'
  Path::Tiny: '0'
  perl: '5.038000'
resources:
  bugtracker: https://github.com/Perl-SDL3/Alien-SDL3.pm/issues
  homepage: https://github.com/Perl-SDL3/Alien-SDL3.pm
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/Perl-SDL3/Alien-SDL3.pm.git
version: v3.4.2
x_authority: cpan:SANKO
x_ignore:
  - .github/FUNDING.yml
  - .github/workflows/ci.yml
  - .github/workflows/delete_cache.yml
  - .gitignore
  - .tidyallrc
  - .clang-format
  - .github/**
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
x_static_install: 0
