name = "Alien-SDL3"
badges = ["github-actions/test.yml", "metacpan"]
# badges = ["github-actions/linux.yaml", "github-actions/windows.yaml", "github-actions/osx.yaml", "github-actions/freebsd.yaml"]
module_maker="ModuleBuild"
static_install = "auto"
authority = "cpan:SANKO"
license = "artistic_2"
markdown_maker = "Pod::Markdown::Github"

[build]
build_class = "builder::Alien"

[release]
hook=[
    'tidyall -a'
]

[Metadata]
X_No_Archive = 'Yes'
