name: test
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows (MSVC+CMake),         os: windows-latest, shell: sh,   cmake: '-DPerl_ROOT=C:/Strawberry/perl/bin/ -GNinja', msvc: 1, shared: 1, static: 0 }
        - { name: Windows (mingw64+CMake),      os: windows-latest, shell: 'msys2 {0}', msystem: mingw64, msys-env: mingw-w64-x86_64, shared: 1, static: 0,
            cmake: '-G "Ninja Multi-Config"' }
        - { name: Linux,                        os: ubuntu-20.04,   shell: sh,   cmake: '-GNinja', shared: 1, static: 0 }
        - { name: 'Linux (static)',             os: ubuntu-20.04,   shell: sh,   cmake: '-GNinja -DBUILD_SHARED_LIBS=OFF', shared: 0, static: 1 }
        - { name: Macos,                        os: macos-latest,   shell: sh,   cmake: '-GNinja', shared: 1, static: 0 }
        perl:
          [
            "5.38",
            "5.36",
            "5.34",
            "5.32",
            "5.30",
            "5.28",
            "5.26",
            "5.24"
          ]
    name: ${{ matrix.perl }} on ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Install dependencies
        run: cpanm --installdeps --with-recommends --with-suggests --with-configure --verbose --notest --mirror http://cpan.cpantesters.org .
      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.platform.msvc }}
        with:
          arch: x64
      - name: Set up Ninja
        if: ${{ !contains(matrix.platform.shell, 'msys2') }}
        uses: aseprite/get-ninja@main
      - name: Set up MSYS2
        if: ${{ matrix.platform.shell == 'msys2 {0}' }}
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.platform.msystem }}
          install: >-
            ${{ matrix.platform.msys-env }}-cmake
            ${{ matrix.platform.msys-env }}-gcc
            ${{ matrix.platform.msys-env }}-freetype
            ${{ matrix.platform.msys-env }}-harfbuzz
            ${{ matrix.platform.msys-env }}-ninja
            ${{ matrix.platform.msys-env }}-perl
            ${{ matrix.platform.msys-env }}-pkg-config
            ${{ matrix.platform.msys-env }}-zlib
      - name: Set up SDL
        id: sdl
        uses: libsdl-org/setup-sdl@main
        with:
          cmake-generator: Ninja
          version: 3-head
          version-sdl-ttf: 3-head
          sdl-test: true
          shell: ${{ matrix.platform.shell }}
      - name: Setup Macos dependencies
        if: ${{ runner.os == 'macOS' }}
        run: |
            brew install \
              freetype \
              harfbuzz \
              pkg-config \
              ${NULL+}
      - name: Set up Linux dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            cmake \
            file \
            fonts-dejavu-core \
            libfreetype-dev \
            libharfbuzz-dev \
            pkg-config \
            ${NULL+}
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run test
        run: cpanm --test-only -v .
