name: test
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        perl:
          [
            "5.38",
            "5.36",
            "5.34",
            "5.32",
            "5.30",
            "5.28",
            "5.26",
            "5.24"
          ]
    name: ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Install dependencies
        run: cpanm --installdeps --with-recommends --with-suggests --with-configure --verbose --notest --mirror http://cpan.cpantesters.org .
      - name: Install SDL3
        uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 3-latest
          version-sdl-image: 3-latest
          version-sdl-mixer: 3-latest
          version-sdl-ttf: 3-latest
          version-sdl-rtf: 3-latest
          add-to-environment: true
      - name: Run test
        run: cpanm --test-only -v .
